### ISSUE TITLE
'training/config_nsf.yaml'로 해야할것같습니다

### ISSUE THREAD

**Issue by popop098** [wlsdml1114/diff-svc#19]
config파일을 자세히 둘러보는중에
```yaml
# training/config.yaml
audio_sample_rate : 24000

# training/config_nsf.yaml
audio_sample_rate : 44100
```
이렇게 샘플레이트가 다르더라구요.

노멀라이징할때 44100으로 변환했으니 'config_nsf.yaml'을 사용해야하지않나 싶습니다.

저 값이 결과물에 관여를 하는지는 정확히 모르겠어서 먼저 이슈로 여쭈어봅니다.
